import React, { createContext, useContext, useState, useEffect, ReactNode } from 'react';

export type Language = 'he' | 'ar' | 'en';

interface LanguageContextType {
  language: Language;
  setLanguage: (lang: Language) => void;
  dir: 'rtl' | 'ltr';
  t: (key: string) => string;
}

const LanguageContext = createContext<LanguageContextType | undefined>(undefined);

export const useLanguage = () => {
  const context = useContext(LanguageContext);
  if (!context) throw new Error('useLanguage must be used within LanguageProvider');
  return context;
};

const translations: Record<Language, Record<string, string>> = {
  he: {
    'app.name': 'מי עירון',
    'app.subtitle': 'תאגיד מים וביוב - עירון',
    'nav.home': 'דף הבית',
    'nav.resident_file': 'תיק תושב',
    'nav.appointments': 'הזמנת תור',
    'nav.forms': 'טפסים',
    'nav.green_bill': 'חשבונית ירוקה',
    'nav.moving': 'העברת דירה',
    'nav.new_line': 'קו מים חדש',
    'nav.tenders': 'מכרזים',
    'nav.payment': 'תשלום חשבון',
    'nav.reports': 'דיווח תקלה',
    'nav.settings': 'הגדרות',
    'nav.dashboard': 'לוח בקרה',
    'search.placeholder': 'חיפוש שירותים...',
    'login.title': 'כניסה למערכת',
    'login.email': 'אימייל',
    'login.password': 'סיסמה',
    'login.submit': 'התחבר',
    'login.loading': 'מתחבר...',
    'login.success': 'התחברת בהצלחה',
    'login.welcome': 'ברוך הבא למערכת מי עירון',
    'login.error': 'שגיאה',
    'login.invalid': 'אימייל או סיסמה שגויים',
    'logout': 'התנתק',
    'otp.title': 'אימות דו-שלבי',
    'otp.description': 'הכנס את הקוד בן 6 הספרות שנשלח לאימייל שלך',
    'otp.verify': 'אמת קוד',
    'otp.verifying': 'מאמת...',
    'otp.expired': 'הקוד פג תוקף, יש לבקש קוד חדש',
    'otp.resend': 'שלח קוד מחדש',
    'otp.back': 'חזרה להתחברות',
    'otp.resend_wait': 'שליחה חוזרת בעוד',
    'otp.seconds': 'שניות',
    'otp.expires_in': 'הקוד יפוג בעוד:',
    'dashboard.stats': 'סטטיסטיקות פניות',
    'dashboard.recent': 'פניות אחרונות',
    'dashboard.total': 'סה"כ פניות',
    'dashboard.in_progress': 'בקשות בתהליך',
    'dashboard.waiting': 'ממתין לסיוע נציג',
    'dashboard.completed': 'בקשות שטופלו',
    'dashboard.exceeded': 'חרגו מזמן סבב',
    'dashboard.exceeded_alert': 'פניות חרגו מזמן סבב!',
    'dashboard.near_alert': 'פניות עומדות לחרוג בקרוב',
    'table.request_number': 'מספר קריאה',
    'table.subject': 'נושא',
    'table.payer': 'מספר משלם',
    'table.status': 'סטאטוס',
    'table.close_date': 'תאריך סגירה',
    'table.id': 'ת.ז.',
    'table.full_name': 'שם מלא',
    'table.actions': 'פעולות',
    'table.search': 'חיפוש חופשי...',
    'table.page': 'עמוד',
    'table.of': 'מתוך',
    'table.results': 'תוצאות',
    'status.new': 'חדש',
    'status.in_progress': 'בתהליך',
    'status.waiting_for_agent': 'ממתין לנציג',
    'status.completed': 'טופל',
    'status.exceeded_time': 'חרג מזמן סבב',
    'settings.title': 'הגדרות מערכת',
    'settings.description': 'נהל את הגדרות זמני הסבב וההתראות',
    'settings.cycle_times': 'זמני סבב',
    'settings.regular_cycle': 'זמן סבב רגיל (ימים)',
    'settings.urgent_cycle': 'זמן סבב דחוף (ימים)',
    'settings.notifications': 'התראות',
    'settings.notify_urgent': 'שלח התראה בדוא"ל עבור פניות דחופות',
    'settings.notify_exceeded': 'התראה על פניות שחרגו מזמן הסבב',
    'settings.save': 'שמור הגדרות',
    'settings.saved': 'נשמר בהצלחה',
    'settings.saved_desc': 'ההגדרות עודכנו בהצלחה',
    'settings.error': 'שגיאה',
    'settings.invalid_email': 'כתובת מייל לא תקינה',
    'settings.email_exists': 'כתובת זו כבר קיימת ברשימה',
    'settings.email_added': 'כתובת המייל נוספה בהצלחה',
    'settings.no_emails': 'לא הוגדרו כתובות מייל להתראות',
    'settings.screen_notify_title': 'התראות שיתוף מסך',
    'settings.screen_notify_desc': 'כתובות מייל שיקבלו התראה כאשר נכנסת שיחה לשיתוף מסך',
    'settings.enter_email': 'הזן כתובת מייל...',
    'settings.add': 'הוסף',
    'settings.add_user_title': 'הוספת משתמש',
    'settings.add_user_desc': 'רישום משתמש חדש למערכת',
    'settings.fill_fields': 'יש למלא אימייל וסיסמה',
    'settings.user_registered': 'המשתמש נרשם בהצלחה',
    'settings.register_error': 'שגיאה ברישום המשתמש',
    'settings.registering': 'רושם...',
    'settings.register_user': 'רשום משתמש',
    'settings.registered_users': 'משתמשים שנרשמו',
    'settings.user_deleted': 'המשתמש נמחק',
    'screen.no_active': 'אין משיבים פעילים כרגע',
    'screen.no_sharing': 'אין משתמשים שמשתפים מסך באתר כרגע',
    'modal.details': 'פרטי פניה',
    'modal.contact': 'פרטי יצירת קשר',
    'modal.phone': 'מספר טלפון',
    'modal.call': 'חייג עכשיו',
    'modal.send_email': 'שליחת מייל',
    'modal.send_sms': 'שליחת SMS',
    'modal.to': 'אל',
    'modal.subject': 'נושא',
    'modal.body': 'תוכן ההודעה',
    'modal.send': 'שלח',
    'theme.light': 'מעבר למצב בהיר',
    'theme.dark': 'מעבר למצב כהה',
    'language': 'שפה',
  },
  ar: {
    'app.name': 'مياه وادي عارة',
    'app.subtitle': 'شركة المياه والصرف الصحي - عيرون',
    'nav.home': 'الصفحة الرئيسية',
    'nav.resident_file': 'ملف السكان',
    'nav.appointments': 'حجز موعد',
    'nav.forms': 'نماذج',
    'nav.green_bill': 'فاتورة خضراء',
    'nav.moving': 'نقل شقة',
    'nav.new_line': 'خط مياه جديد',
    'nav.tenders': 'مناقصات',
    'nav.payment': 'دفع الفاتورة',
    'nav.reports': 'الإبلاغ عن عطل',
    'nav.settings': 'الإعدادات',
    'nav.dashboard': 'لوحة التحكم',
    'search.placeholder': 'البحث عن الخدمات...',
    'login.title': 'تسجيل الدخول',
    'login.email': 'البريد الإلكتروني',
    'login.password': 'كلمة المرور',
    'login.submit': 'تسجيل الدخول',
    'login.loading': 'جارٍ الاتصال...',
    'login.success': 'تم الاتصال بنجاح',
    'login.welcome': 'مرحبًا بك في نظام مياه عيرون',
    'login.error': 'خطأ',
    'login.invalid': 'بريد إلكتروني أو كلمة مرور غير صحيحة',
    'logout': 'تسجيل الخروج',
    'otp.title': 'التحقق بخطوتين',
    'otp.description': 'أدخل الرمز المكون من 6 أرقام المرسل إلى بريدك',
    'otp.verify': 'تحقق',
    'otp.verifying': 'جارٍ التحقق...',
    'otp.expired': 'انتهت صلاحية الرمز',
    'otp.resend': 'إعادة إرسال الرمز',
    'otp.back': 'العودة لتسجيل الدخول',
    'otp.resend_wait': 'إعادة الإرسال خلال',
    'otp.seconds': 'ثوانٍ',
    'otp.expires_in': 'ينتهي الرمز خلال:',
    'dashboard.stats': 'إحصائيات الطلبات',
    'dashboard.recent': 'الطلبات الأخيرة',
    'dashboard.total': 'إجمالي الطلبات',
    'dashboard.in_progress': 'قيد المعالجة',
    'dashboard.waiting': 'بانتظار ممثل',
    'dashboard.completed': 'تمت المعالجة',
    'dashboard.exceeded': 'تجاوزت الوقت',
    'dashboard.exceeded_alert': 'طلبات تجاوزت الوقت!',
    'dashboard.near_alert': 'طلبات على وشك التجاوز',
    'table.request_number': 'رقم الطلب',
    'table.subject': 'الموضوع',
    'table.payer': 'رقم الدافع',
    'table.status': 'الحالة',
    'table.close_date': 'تاريخ الإغلاق',
    'table.id': 'هوية',
    'table.full_name': 'الاسم الكامل',
    'table.actions': 'إجراءات',
    'table.search': 'بحث حر...',
    'table.page': 'صفحة',
    'table.of': 'من',
    'table.results': 'نتائج',
    'status.new': 'جديد',
    'status.in_progress': 'قيد المعالجة',
    'status.waiting_for_agent': 'بانتظار ممثل',
    'status.completed': 'تمت المعالجة',
    'status.exceeded_time': 'تجاوز الوقت',
    'settings.title': 'إعدادات النظام',
    'settings.description': 'إدارة أوقات الدورة والإشعارات',
    'settings.cycle_times': 'أوقات الدورة',
    'settings.regular_cycle': 'وقت الدورة العادي (أيام)',
    'settings.urgent_cycle': 'وقت الدورة العاجل (أيام)',
    'settings.notifications': 'الإشعارات',
    'settings.notify_urgent': 'إرسال تنبيه للطلبات العاجلة',
    'settings.notify_exceeded': 'تنبيه للطلبات التي تجاوزت الوقت',
    'settings.save': 'حفظ الإعدادات',
    'settings.saved': 'تم الحفظ',
    'settings.saved_desc': 'تم تحديث الإعدادات بنجاح',
    'settings.error': 'خطأ',
    'settings.invalid_email': 'بريد إلكتروني غير صالح',
    'settings.email_exists': 'هذا البريد موجود بالفعل',
    'settings.email_added': 'تمت إضافة البريد بنجاح',
    'settings.no_emails': 'لم يتم تحديد عناوين بريد للتنبيهات',
    'settings.screen_notify_title': 'تنبيهات مشاركة الشاشة',
    'settings.screen_notify_desc': 'عناوين البريد التي ستتلقى تنبيهاً عند دخول مكالمة مشاركة شاشة',
    'settings.enter_email': 'أدخل بريد إلكتروني...',
    'settings.add': 'إضافة',
    'settings.add_user_title': 'إضافة مستخدم',
    'settings.add_user_desc': 'تسجيل مستخدم جديد في النظام',
    'settings.fill_fields': 'يرجى ملء البريد وكلمة المرور',
    'settings.user_registered': 'تم تسجيل المستخدم بنجاح',
    'settings.register_error': 'خطأ في تسجيل المستخدم',
    'settings.registering': 'جارٍ التسجيل...',
    'settings.register_user': 'تسجيل مستخدم',
    'settings.registered_users': 'المستخدمون المسجلون',
    'settings.user_deleted': 'تم حذف المستخدم',
    'screen.no_active': 'لا يوجد مشاركون نشطون حاليًا',
    'screen.no_sharing': 'لا يوجد مستخدمون يشاركون الشاشة',
    'modal.details': 'تفاصيل الطلب',
    'modal.contact': 'معلومات الاتصال',
    'modal.phone': 'رقم الهاتف',
    'modal.call': 'اتصل الآن',
    'modal.send_email': 'إرسال بريد',
    'modal.send_sms': 'إرسال SMS',
    'modal.to': 'إلى',
    'modal.subject': 'الموضوع',
    'modal.body': 'محتوى الرسالة',
    'modal.send': 'إرسال',
    'theme.light': 'الوضع الفاتح',
    'theme.dark': 'الوضع الداكن',
    'language': 'اللغة',
  },
  en: {
    'app.name': 'Mei Eiron',
    'app.subtitle': 'Water & Sewage Corporation - Eiron',
    'nav.home': 'Home',
    'nav.resident_file': 'Resident File',
    'nav.appointments': 'Appointments',
    'nav.forms': 'Forms',
    'nav.green_bill': 'Green Bill',
    'nav.moving': 'Moving',
    'nav.new_line': 'New Water Line',
    'nav.tenders': 'Tenders',
    'nav.payment': 'Bill Payment',
    'nav.reports': 'Report Issue',
    'nav.settings': 'Settings',
    'nav.dashboard': 'Dashboard',
    'search.placeholder': 'Search services...',
    'login.title': 'Login',
    'login.email': 'Email',
    'login.password': 'Password',
    'login.submit': 'Login',
    'login.loading': 'Connecting...',
    'login.success': 'Login successful',
    'login.welcome': 'Welcome to Mei Eiron',
    'login.error': 'Error',
    'login.invalid': 'Invalid email or password',
    'logout': 'Logout',
    'otp.title': 'Two-Factor Auth',
    'otp.description': 'Enter the 6-digit code sent to your email',
    'otp.verify': 'Verify',
    'otp.verifying': 'Verifying...',
    'otp.expired': 'Code expired, request a new one',
    'otp.resend': 'Resend code',
    'otp.back': 'Back to login',
    'otp.resend_wait': 'Resend in',
    'otp.seconds': 'seconds',
    'otp.expires_in': 'Code expires in:',
    'dashboard.stats': 'Request Statistics',
    'dashboard.recent': 'Recent Requests',
    'dashboard.total': 'Total Requests',
    'dashboard.in_progress': 'In Progress',
    'dashboard.waiting': 'Waiting for Agent',
    'dashboard.completed': 'Completed',
    'dashboard.exceeded': 'Exceeded Time',
    'dashboard.exceeded_alert': 'requests exceeded cycle time!',
    'dashboard.near_alert': 'requests about to exceed',
    'table.request_number': 'Request #',
    'table.subject': 'Subject',
    'table.payer': 'Payer #',
    'table.status': 'Status',
    'table.close_date': 'Close Date',
    'table.id': 'ID',
    'table.full_name': 'Full Name',
    'table.actions': 'Actions',
    'table.search': 'Free search...',
    'table.page': 'Page',
    'table.of': 'of',
    'table.results': 'results',
    'status.new': 'New',
    'status.in_progress': 'In Progress',
    'status.waiting_for_agent': 'Waiting',
    'status.completed': 'Completed',
    'status.exceeded_time': 'Exceeded',
    'settings.title': 'System Settings',
    'settings.description': 'Manage cycle times and notifications',
    'settings.cycle_times': 'Cycle Times',
    'settings.regular_cycle': 'Regular cycle (days)',
    'settings.urgent_cycle': 'Urgent cycle (days)',
    'settings.notifications': 'Notifications',
    'settings.notify_urgent': 'Email alerts for urgent requests',
    'settings.notify_exceeded': 'Alert on exceeded cycle time',
    'settings.save': 'Save Settings',
    'settings.saved': 'Saved',
    'settings.saved_desc': 'Settings updated successfully',
    'settings.error': 'Error',
    'settings.invalid_email': 'Invalid email address',
    'settings.email_exists': 'This email already exists',
    'settings.email_added': 'Email added successfully',
    'settings.no_emails': 'No notification emails configured',
    'settings.screen_notify_title': 'Screen Share Notifications',
    'settings.screen_notify_desc': 'Email addresses that will be notified when a screen share session starts',
    'settings.enter_email': 'Enter email address...',
    'settings.add': 'Add',
    'settings.add_user_title': 'Add User',
    'settings.add_user_desc': 'Register a new user to the system',
    'settings.fill_fields': 'Please fill in email and password',
    'settings.user_registered': 'User registered successfully',
    'settings.register_error': 'Error registering user',
    'settings.registering': 'Registering...',
    'settings.register_user': 'Register User',
    'settings.registered_users': 'Registered Users',
    'settings.user_deleted': 'User deleted',
    'screen.no_active': 'No active respondents',
    'screen.no_sharing': 'No users sharing screen currently',
    'modal.details': 'Request Details',
    'modal.contact': 'Contact Info',
    'modal.phone': 'Phone Number',
    'modal.call': 'Call Now',
    'modal.send_email': 'Send Email',
    'modal.send_sms': 'Send SMS',
    'modal.to': 'To',
    'modal.subject': 'Subject',
    'modal.body': 'Message',
    'modal.send': 'Send',
    'theme.light': 'Switch to light mode',
    'theme.dark': 'Switch to dark mode',
    'language': 'Language',
  },
};

export const LanguageProvider: React.FC<{ children: ReactNode }> = ({ children }) => {
  const [language, setLanguage] = useState<Language>(() => {
    return (localStorage.getItem('meieiron_lang') as Language) || 'he';
  });

  const dir = language === 'en' ? 'ltr' : 'rtl';

  useEffect(() => {
    localStorage.setItem('meieiron_lang', language);
    document.documentElement.setAttribute('dir', dir);
    document.documentElement.setAttribute('lang', language);
  }, [language, dir]);

  const t = (key: string): string => translations[language][key] || key;

  return (
    <LanguageContext.Provider value={{ language, setLanguage, dir, t }}>
      {children}
    </LanguageContext.Provider>
  );
};
